; /etc/supervisor/conf.d/gostay-worker.conf
; Reload after changes: sudo supervisorctl reread && sudo supervisorctl update

[program:gostay-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/gostay/current/artisan queue:work database --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=deploy
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/gostay/shared/storage/logs/worker.log
stopwaitsecs=3600
